# Generated by Django 4.2.4 on 2023-08-12 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_taskmodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='status',
        ),
    ]
