# Generated by Django 4.2.4 on 2023-08-23 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('prod_slug', models.SlugField(max_length=200, unique=True)),
                ('prod_descri', models.TextField(blank=True, max_length=500)),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prod_img', models.ImageField(upload_to='photos/products')),
                ('prod_stock', models.IntegerField()),
                ('is_avaiable', models.BooleanField(default=False)),
                ('prod_created_date', models.DateTimeField(auto_now_add=True)),
                ('prod_modify_date', models.DateTimeField(auto_now=True)),
                ('prod_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='category_app.categorymodel')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
