# Generated by Django 4.2.3 on 2023-08-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0002_student_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.TextField(blank=True, default='Rahim'),
        ),
    ]
