# Generated by Django 4.2.3 on 2023-08-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0002_employeemodel_managermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=40)),
                ('attandence', models.BooleanField()),
                ('home_work', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app8.friend',),
        ),
    ]
