# Generated by Django 4.2.3 on 2023-08-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0004_person_passpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passpost',
            name='passport_num',
            field=models.CharField(max_length=40),
        ),
    ]
