# Generated by Django 4.2.3 on 2023-08-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0006_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('roll', models.IntegerField()),
                ('class_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('sutdent_m', models.ManyToManyField(to='app8.student')),
            ],
        ),
    ]
