# Generated by Django 4.2.3 on 2023-08-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('father_name', models.CharField(max_length=40)),
                ('address', models.TextField()),
            ],
        ),
    ]
