# Generated by Django 4.2.4 on 2023-08-21 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionmodel',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='ammount',
            new_name='amount',
        ),
    ]
