# Generated by Django 4.2.4 on 2023-08-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_app', '0002_alter_transactionmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='balance_after_transaction',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
