# Generated by Django 4.2.4 on 2023-08-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_app', '0004_alter_transactionmodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=12, null=True),
        ),
    ]
