# Generated by Django 4.2.4 on 2023-08-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_app', '0005_alter_transactionmodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=12),
        ),
    ]
