# Generated by Django 4.2.4 on 2023-08-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_app', '0007_alter_transactionmodel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='transfer_account',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Loan'), (4, 'Loan Paid'), (5, 'Transfer Money')]),
        ),
    ]
