# Generated by Django 4.2.4 on 2023-08-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_app', '0008_transactionmodel_transfer_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='transfer_account',
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='transfer',
            field=models.IntegerField(null=True),
        ),
    ]
