# Generated by Django 4.2.4 on 2023-08-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_app', '0009_remove_transactionmodel_transfer_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='transfer',
        ),
    ]
